server:
  port: 18001
spring:
  application:
    name: "eureka-service"
eureka:
  instance:
    hostname: "127.0.0.1"
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: "http://127.0.0.1:18000/eureka/,http://127.0.0.1:18002/eureka/"
  server:
    enable-self-preservation: false
